### ISSUE TITLE
unable to auth

### ISSUE THREAD

**Issue by netmonk** [firebase/firereader#45]
Good morning folks. 

After a fresh install cloned from github,
After a fresh account creation on firebase, 
After a fresh application creation on twitter and github, 
After a fresh installation of nginx for serving the file, 

Im UNABLE TO LOGIN. 

Twitter auth give this message : {"error":{"message":"Route not found","code":404}}
from https://auth.firebase.com/auth/twitter?firebase=resplendent-fire-7213&scope=email

Github auth gives no message at all, and trigger a JS error 
[object Object]
https://ajax.googleapis.com/ajax/libs/angularjs/1.2.15/angular.js
Line 9563

I have a free dev plan on firebase for information

**Comment by RudthMael** [comment]
I have the same problem. Did you figure it out?

**Comment by netmonk** [comment]
No I gave up !
Le 4 Jan. 2015 18:25, "Rudth-Mael Galite" <notifications@github.com> a
écrit :

**Comment by jaan** [comment]
I removed the API keys in firebase for twitter and added it back. Toggled the "Enable Twitter Authentication" few times and it started working.

**Comment by sirhodes** [comment]
also having this issue, help?

**Comment by katowulf** [comment]
Unable to auth is an extremely broad subject and "having the same issue" is unlikely, given such a vast area with as many moving parts. 

Please submit separate issues with specific details to reproduce (see [creating an mcve](http://stackoverflow.com/help/mcve)), unless you can see from specific steps, details, and versions that you actually have the exact same use case with repro steps. 

I'm going to lock this issue for now to prevent these "me too" responses until more detailed problem sets are posted. This should help us get to some actual problem sets that can be addressed.
